feature(parallized deploy): allow configuration of the deployer to run tasks in parallel (per leaf node)
simpligility/maven-repository-tools pull request #74
Opened 2024-10-18 22:13 UTC by dakaneye

**Summary of Changes**
- Configuration: Adds a deployThreads configuration.
- MavenRepositoryDeployer: establishes this class as a Singleton
- MavenRepositoryDeploymentCallable: for a given leaf node, this does the deployment, returning a new DeploymentResult object to collect for the overall summary

2024-10-18 22:14 UTC, dakaneye commented
@mosabua FYI! I couldn't get the checkstyle to pass locally, would you be interested in porting over to spotless?

2024-10-20 01:08 UTC, mosabua commented
Please change commit messages to follow https://trino.io/development/process#pull-request-and-commit-guidelines-

2024-10-20 01:41 UTC, mosabua requested changes
Had a first look .. once its compiles I can do some testing ..

2024-10-20 01:41 UTC, mosabua commented on maven-repository-provisioner/src/test/java/com/simpligility/maven/provisioner/MavenRepositoryDeploymentCallableTest.java
> +public class MavenRepositoryDeploymentCallableTest
awesome .. definitely need more tests overall ;-)

2024-10-20 01:41 UTC, mosabua commented on maven-repository-provisioner/src/test/java/com/simpligility/maven/provisioner/helpers/RepositorySystemImpl.java
> +import org.eclipse.aether.RepositorySystem;
We should really move to the newer version of aether or the maven resolver replacement .. but that can follow later cc @cstamas

2024-10-20 04:41 UTC, dakaneye commented on .gitignore
> +**/*.iml
i'm not 100% sure how it ended up in git tracking, but I had one generated when I tried to add some checkstyle plugins to my intellij.

2024-10-22 20:56 UTC, cstamas commented
Folks, unsure what you want to achieve, but parallel deploy in Resolver 1.9+ is a thing. All you need is to "batch" the deploy request. See https://issues.apache.org/jira/browse/MRESOLVER-319

2024-10-22 21:02 UTC, mosabua commented
> Folks, unsure what you want to achieve, but parallel deploy in Resolver 1.9+ is a thing. All you need is to "batch" the deploy request. See https://issues.apache.org/jira/browse/MRESOLVER-319


I vaguely remember now .. but yes.. for that to be used we have to upgrade this project to the new resolver stuff .. which arguably would be good.

2024-10-22 21:02 UTC, closed without merging