Add a configuration to specify a filter file for what to deploy
simpligility/maven-repository-tools pull request #82
Opened 2024-10-28 16:49 UTC by dakaneye

Adds a -df -deployFilterfile configuration that is a file path to load for telling the MavenRepositoryDeployer which GAVs to deploy. This file contains a groupId:artifactId:version:ext per line, and is loaded into memory as a Set<Gav>. It implements the Object.equals method on Gav so that we can compare GAVs in order to know if it is in the filter file or not. If the filter file is not specified, or doesnt exist, we do not filter at all.

Fixes: https://github.com/simpligility/maven-repository-tools/issues/81

2024-10-29 03:13 UTC, mosabua commented
I will review after merge for other PR and rebase.

Generally looks good. 

For commit message:

```
Add configuration filter to narrow deployment
```

and maybe have a little paragraph that details that this allows to define artifacts that are in .. not out.

2024-10-29 15:49 UTC, mosabua commented
Please rebase .. needed since I merged the other PR..

2024-11-01 04:23 UTC, dakaneye commented
@mosabua should be ready for a review now!

2024-11-04 17:00 UTC, mosabua requested changes
Threw in a few comments .. overall I think this is great. Just need to improve user facing docs a bit probably.

2024-11-04 22:26 UTC, dakaneye commented on maven-repository-provisioner/src/main/java/com/simpligility/maven/provisioner/MavenRepositoryDeployer.java
> +                logger.info("Skipping deployment of " + gav + " as it is not in the deploy filter file.");
I added support for this in the GavPattern :)

2024-11-04 22:54 UTC, mosabua commented on maven-repository-provisioner/src/main/java/com/simpligility/maven/provisioner/MavenRepositoryDeployer.java
> +                logger.info("Skipping deployment of " + gav + " as it is not in the deploy filter file.");
nice!

2024-11-04 23:10 UTC, mosabua approved these changes
I think this looks good enough for now. The difference between extension and packaging for the filter and in general the filtering below groupId (so artifactId, version, extension/packaging) will probably have to be improved over time.

Not sure if we should enforce a standard so that only what we actually support and test is valid .. 

So not allow stuff like `com.*:*:*` or `*:*:0.*:*` or `*:*:*:javadoc` at all in the config file parsing since we dont actually support it. 

Thoughts @dakaneye and @jvanzyl ?

Should we merge, cut a release and then improve after as we see during usage?

2024-11-05 00:13 UTC, dakaneye commented
> Not sure if we should enforce a standard so that only what we actually support and test is valid ..
> 
> So not allow stuff like `com.*:*:*` or `*:*:0.*:*` or `*:*:*:javadoc` at all in the config file parsing since we dont actually support it.

It seems probably better to make sure that groupId and artifactId (at least) and version? are set otherwise yeah, this isn't much of a filter. Then again, it is reading a local repo, not a remote to deploy from, so maybe it's fine.

2024-11-05 00:21 UTC, mosabua commented
Yeah, if it works for your use case .. then lets restrict it to what works and is useful and no allow other patterns in the config file

2024-11-06 02:11 UTC, mosabua commented
Please fix build .. then I think we can go ahead and merge and release. More improvements can in follow ups.

2024-11-06 16:40 UTC, merged